import {
  house,
  shorts,
  subscription,
  youtube,
  library,
  music,
  download,
  trending,
  bag,
  musicNote,
  movie,
  game,
  news,
  live,
  bulb,
  fashion,
  cup,
  settings,
  feedback,
  help,
  flag,
  profile,
  switchAccount,
  ytStudio,
  signout,
  dollar,
  premium,
  data,
  moon,
  language,
  restrict,
  location,
  settingslight,
  keyboard,
  helplight,
  feedbacklight,
  rightarrow,
  menudark,
  micdark,
  searchdark,
  belldark,
  createdark,
  housedark,
  shortsdark,
  subscriptiondark,
  youtubedark,
  librarydark,
  musicdark,
  downloaddark,
  trendingdark,
  bagdark,
  musicNotedark,
  moviedark,
  gamedark,
  newsdark,
  livedark,
  bulbdark,
  fashiondark,
  cupdark,
  settingsdark,
  feedbackdark,
  helpdark,
  flagdark,
  profiledark,
  ytStudiodark,
  switchdark,
  signindark,
  dollardark,
  shielddark,
  moondark,
  languagedark,
  locationdark,
  keyboarddark,
  settingslightdark,
  helplightdark,
  feedbacklightdark,
  rightarrowdark,
  restrictdark,
  ytmusicdark,
  youtubemusic,
  youtubekids,
  youtubestudio,
  watchlaterdark,
  watchlaterlight,
} from "../assets";

export const categories = [
  {
    id: 1,
    title: "Home",
    lightimg: house,
    darkimg: housedark,
    url: "home",
    status: false,
    to: "/",
  },
  {
    id: 2,
    title: "Shorts",
    lightimg: shorts,
    darkimg: shortsdark,
    url: "shorts",
    status: false,
    to: "/shorts/:id",
  },
  {
    id: 3,
    title: "Subscriptions",
    lightimg: subscription,
    darkimg: subscriptiondark,
    url: "home",
    status: false,
    to: "/subscriptions",
  },
  {
    id: 4,
    title: "Originals",
    lightimg: youtube,
    darkimg: youtubedark,
    url: "youtube%20originals",
    status: false,
    to: "/originals",
  },
  {
    id: 5,
    title: "Youtube Music",
    lightimg: music,
    darkimg: ytmusicdark,
    status: true,
    to: "https://music.youtube.com",
  },
  {
    id: 6,
    title: "Library",
    lightimg: library,
    darkimg: librarydark,
    status: false,
    to: "/library",
  },
  {
    id: 7,
    title: "Downloads",
    lightimg: download,
    darkimg: downloaddark,
    status: false,
    to: "/downloads",
  },
  {
    id: 8,
    title: "Watch Later",
    lightimg: watchlaterlight,
    darkimg: watchlaterdark,
    status: true,
    to: "/watchlater",
  },
  {
    id: 9,
    title: "Trending",
    lightimg: trending,
    darkimg: trendingdark,
    url: "trending",
    status: false,
    to: "/",
  },
  {
    id: 10,
    title: "Shopping",
    lightimg: bag,
    darkimg: bagdark,
    url: "shopping",
    status: false,
    to: "/",
  },
  {
    id: 11,
    title: "Music",
    lightimg: musicNote,
    darkimg: musicdark,
    url: "music",
    status: false,
    to: "/",
  },
  {
    id: 12,
    title: "Movies & shows",
    lightimg: movie,
    darkimg: moviedark,
    url: "movies%20&%20shows",
    status: false,
    to: "/",
  },
  {
    id: 13,
    title: "Live",
    lightimg: live,
    darkimg: livedark,
    url: "live",
    status: false,
    to: "/",
  },
  {
    id: 14,
    title: "Gaming",
    lightimg: game,
    darkimg: gamedark,
    url: "gaming",
    status: false,
    to: "/",
  },
  {
    id: 15,
    title: "News",
    lightimg: news,
    darkimg: newsdark,
    url: "news",
    status: false,
    to: "/",
  },
  {
    id: 16,
    title: "Sports",
    lightimg: cup,
    darkimg: cupdark,
    url: "sports",
    status: false,
    to: "/",
  },
  {
    id: 17,
    title: "Leaning",
    lightimg: bulb,
    darkimg: bulbdark,
    url: "education",
    status: false,
    to: "/",
  },
  {
    id: 18,
    title: "Fashion & beauty",
    lightimg: fashion,
    darkimg: fashiondark,
    url: "fashion",
    status: true,
    to: "/",
  },
  {
    id: 19,
    title: "YouTube Studio",
    to: "https://studio.youtube.com",
    lightimg: youtubestudio,
    darkimg: youtubestudio,
  },
  {
    id: 20,
    title: "YouTube Music",
    to: "https://music.youtube.com",
    lightimg: youtubemusic,
    darkimg: youtubemusic,
  },
  {
    id: 21,
    title: "YouTube Kids",
    to: "https://www.youtubekids.com/?source=youtube_web",
    lightimg: youtubekids,
    darkimg: youtubekids,
    status: true,
  },
  {
    id: 22,
    title: "Settings",
    lightimg: settings,
    darkimg: settingsdark,
  },
  {
    id: 23,
    title: "Report history",
    lightimg: flag,
    darkimg: flagdark,
  },
  {
    id: 24,
    title: "Help",
    lightimg: help,
    darkimg: helpdark,
  },
  {
    id: 25,
    title: "Send fedback",
    lightimg: feedback,
    darkimg: feedbackdark,
  },
];

export const dropdown_options = [
  {
    id: 1,
    title: "Your channel",
    lightimg: profile,
    darkimg: profiledark,
    status: false,
  },
  {
    id: 2,
    title: "YouTube Studio",
    lightimg: ytStudio,
    darkimg: ytStudiodark,
    status: false,
  },
  {
    id: 3,
    title: "Switch account",
    lightimg: switchAccount,
    darkimg: profiledark,
    arrow: rightarrow,
    darkarrow: rightarrowdark,
    status: false,
  },
  {
    id: 4,
    title: "Sign out",
    lightimg: signout,
    darkimg: signindark,
    status: true,
  },
  {
    id: 5,
    title: "Your Premium benefits",
    lightimg: premium,
    darkimg: premium,
    status: false,
  },
  {
    id: 6,
    title: "Purchases and membersips",
    lightimg: dollar,
    darkimg: dollardark,
    status: false,
  },
  {
    id: 7,
    title: "Your data in YouTube",
    lightimg: data,
    darkimg: shielddark,
    status: true,
  },
  {
    id: 9,
    title: "Language: British English",
    lightimg: language,
    darkimg: languagedark,
    status: false,
    darkarrow: rightarrowdark,
    arrow: rightarrow,
  },
  {
    id: 10,
    title: "Restricted Mode: on",
    lightimg: restrict,
    darkimg: restrictdark,
    status: false,
    arrow: rightarrow,
    darkarrow: rightarrowdark,
  },
  {
    id: 11,
    title: "Location: India",
    lightimg: location,
    darkimg: locationdark,
    status: false,
    arrow: rightarrow,
    darkarrow: rightarrowdark,
  },
  {
    id: 12,
    title: "Keyboard shortcuts",
    lightimg: keyboard,
    darkimg: keyboarddark,
    darkarrow: rightarrowdark,
    status: true,
  },
  {
    id: 13,
    title: "Settings",
    lightimg: settingslight,
    darkimg: settingslightdark,
    status: false,
  },
  {
    id: 14,
    title: "Help",
    lightimg: helplight,
    darkimg: helplightdark,
    status: false,
  },
  {
    id: 15,
    title: "Send feedback",
    lightimg: feedbacklight,
    darkimg: feedbacklightdark,
    status: false,
  },
];

export const top_options = [
  {
    id: 1,
    title: "All",
    url: "home",
  },
  {
    id: 2,
    title: "Fun",
    url: "fun",
  },
  {
    id: 3,
    title: "Live",
    url: "Live",
  },
  {
    id: 4,
    title: "Music",
    url: "music",
  },
  {
    id: 5,
    title: "Tarak Mehta Ka Ooltah Chashmah",
    url: "tarak mehta ka ooltah chashmah",
  },
  {
    id: 6,
    title: "Dramedy",
    url: "dramedy",
  },
  {
    id: 7,
    title: "Trailers",
    url: "trailers",
  },
  {
    id: 8,
    title: "Game shows",
    url: "game shows",
  },
  {
    id: 9,
    title: "Bollywood Music",
    url: "bollywood music",
  },
  {
    id: 10,
    title: "Gaming",
    url: "gaming",
  },
  {
    id: 11,
    title: "Lo-fi",
    url: "lofi",
  },
  {
    id: 12,
    title: "Cricket",
    url: "cricket",
  },
  {
    id: 13,
    title: "Motivation",
    url: "motivation",
  },
  {
    id: 14,
    title: "Indain cuisine",
    url: "indain cuisine",
  },
  {
    id: 15,
    title: "Physics",
    url: "physics",
  },
  {
    id: 16,
    title: "Universe",
    url: "universe",
  },
  {
    id: 17,
    title: "Cars",
    url: "cars",
  },
  {
    id: 18,
    title: "Recently Uploaded",
    url: "recently uploaded",
  },
];
